# Generated by Django 5.1.2 on 2024-10-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0001_initial'),
        ('app_transaction', '0005_alter_historicaltopup_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltopup',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_agent.paymentprovider'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_agent.paymentprovider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_agent.paymentprovider'),
        ),
    ]
