# Generated by Django 5.1.2 on 2024-10-20 09:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_merchant', '0006_alter_historicalmerchant_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('soft_deleted', 'Soft Deleted')], default='inactive', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('paymentID', models.CharField(db_index=True, max_length=100)),
                ('trxID', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('merchantInvoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('payerType', models.CharField(blank=True, max_length=50, null=True)),
                ('payerReference', models.CharField(blank=True, max_length=15, null=True)),
                ('customerMsisdn', models.CharField(blank=True, max_length=15, null=True)),
                ('payerAccount', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_merchant.merchant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical payment',
                'verbose_name_plural': 'historical payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('soft_deleted', 'Soft Deleted')], default='inactive', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('paymentID', models.CharField(max_length=100, unique=True)),
                ('trxID', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('merchantInvoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('payerType', models.CharField(blank=True, max_length=50, null=True)),
                ('payerReference', models.CharField(blank=True, max_length=15, null=True)),
                ('customerMsisdn', models.CharField(blank=True, max_length=15, null=True)),
                ('payerAccount', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_merchant.merchant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
