# Generated by Django 5.1.2 on 2024-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
