# Generated by Django 5.1.2 on 2024-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_historicalpayment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
    ]
