# Generated by Django 5.1.2 on 2024-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0003_alter_historicalpayment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('rejected', 'rejected'), ('failed', 'failed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('rejected', 'rejected'), ('failed', 'failed')], default='pending', max_length=255),
        ),
    ]
