# Generated by Django 5.1.2 on 2024-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0004_alter_historicalpayment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='trxID',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trxID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
