# Generated by Django 4.2.16 on 2024-10-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0007_currencyexchangerate'),
    ]

    operations = [
    ]
