# Generated by Django 4.2.16 on 2024-10-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0008_auto_20241028_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='after_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('prepayment', 'Prepayment'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='prepayment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='after_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('prepayment', 'Prepayment'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='prepayment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
