# Generated by Django 4.2.16 on 2024-10-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0009_historicalpayment_after_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='in_bdt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='in_bdt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
