# Generated by Django 4.2.16 on 2024-10-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0011_historicalpayment_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAddressTRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
