# Generated by Django 4.2.16 on 2024-10-28 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0012_cryptoaddresstrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='address_trc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_payment.cryptoaddresstrc'),
        ),
        migrations.AddField(
            model_name='payment',
            name='address_trc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_address_trc', to='app_payment.cryptoaddresstrc'),
        ),
    ]
