# Generated by Django 5.1.2 on 2024-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='password',
            field=models.CharField(default='2024-01-01', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='phone_number',
            field=models.CharField(default='2024-01-01', max_length=20),
            preserve_default=False,
        ),
    ]
