# Generated by Django 5.1.2 on 2024-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0002_paymentprovider_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='BDT', max_length=50),
        ),
    ]
