# Generated by Django 5.1.1 on 2024-10-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0005_alter_paymentprovider_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider',
            field=models.CharField(choices=[('bkash', 'BKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='bkash', max_length=50),
        ),
    ]
