# Generated by Django 4.2.16 on 2024-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0006_alter_paymentprovider_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='bank_id',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='trx_type',
            field=models.CharField(default='2024-01-01', max_length=50),
            preserve_default=False,
        ),
    ]
