# Generated by Django 4.2.16 on 2024-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0007_paymentprovider_bank_id_paymentprovider_trx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider',
            field=models.CharField(choices=[('bkash', 'bkash'), ('nagad', 'nagad')], default='bkash', max_length=50),
        ),
    ]
