# Generated by Django 4.2.16 on 2024-10-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0008_alter_paymentprovider_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(default='2024-01-01', max_length=200),
            preserve_default=False,
        ),
    ]
