# Generated by Django 4.2.16 on 2024-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agent', '0010_paymentprovider_maximum_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
